version: "3.8"

services:
  app:
    image: newmohib/node-docker-nginx-sample-app:jenkins-1.0.1 # Replace with your custom image name
    container_name: node-docker-nginx-sample-app
    restart: always
    depends_on:
      - db
    environment:
      NODE_ENV: dev
      DATABASE_URL: postgres://postgres:postgres@db:5432/mydatabase # Update if needed
    ports:
      - "4000:4000"
    networks:
      - my_network

  db:
    image: postgres:15 # Use the required PostgreSQL version
    container_name: my_postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my_network

networks:
  my_network:

volumes:
  postgres_data:
